
output:
  file: SystematicsE2C.root
  histogram: E2CCombined
nominal:
  file: unfoldingE2C_DoubleLogBinning_07082024.root
  histogram: Bayesian_Unfoldediter2
systematics:
  IterationCount:
    base_type: nominal
    variant_type: file
    variant_file: unfoldingE2C_DoubleLogBinning_07082024.root
    variant_histogram: Bayesian_Unfoldediter3
  FlatEfficiency:
    base_type: nominal
    variant_type: scale
    variant_scale: 1.01
  MCBinning:
    base_type: nominal
    variant_type: 1dratio
    variant_file: unfoldingE2C_DoubleLogBinning_FrozenMCBinning_09232024.root
    variant_numerator:
    variant_denominator:
    variant_scale: 0.5

